import './globals.css';
import { Roboto_Mono } from 'next/font/google';

const roboto = Roboto_Mono({ subsets: ['latin'] });

export const metadata = {
	title: 'Keyboard Champ',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<head>
				<link rel='icon' href='/favicon.svg' sizes='any' />
			</head>
			<body className={roboto.className}>{children}</body>
		</html>
	);
}
